export enum GameEvents
{
    REGISTER_GAME = 'REGISTER_GAME',

    PRELOADING_START = 'PRELOADING_START',
    PRELOADING_PROGRESS = 'PRELOADING_PROGRESS',
    PRELOADING_DONE = 'PRELOADING_DONE',

    GAME_STARTED = 'GAME_STARTED',
    GAME_RESET = 'GAME_RESET',
    FINISH_PLAY = 'FINISH_PLAY',
    FINISH_SPIN = 'FINISH_SPIN',
    FREE_STOP_BUTTON = 'FREE_STOP_BUTTON',
    LOCK_STOP_BUTTON = 'LOCK_STOP_BUTTON',

    TRIGGER_EVENT = 'TRIGGER_EVENT',
    TRIGGER_EVENT_SPIN = 'TRIGGER_EVENT_SPIN',
    TRIGGER_SEND_GAMBLE = 'TRIGGER_SEND_GAMBLE',
    TRIGGER_FINISH_GAMBLE = 'TRIGGER_FINISH_GAMBLE',

    GET_MONEY_FORMATTER = 'GET_MONEY_FORMATTER',

    UPDATE_SIDE_BET = 'UPDATE_SIDE_BET',
    UPDATE_FREESPINS_PANEL = 'UPDATE_FREESPINS_PANEL',
    UPDATE_TUMBLE_WIN = 'UPDATE_TUMBLE_WIN',

    UPDATE_PAYTABLE = 'UPDATE_PAYTABLE',
    UPDATE_RULES = 'UPDATE_RULES',
    UPDATE_RULES_URL = 'UPDATE_RULES_URL',

    NEXT_HISTORY = 'NEXT_HISTORY',
    CLOSE_HISTORY = 'CLOSE_HISTORY',

    HIDE_WRAPPER_UI = 'HIDE_WRAPPER_UI',
    SHOW_WRAPPER_UI = 'SHOW_WRAPPER_UI',
    HIDE_BUTTONS = 'HIDE_BUTTONS',
    SHOW_BUTTONS = 'SHOW_BUTTONS',
    DISABLE_BUTTONS = 'DISABLE_BUTTONS',
    ENABLE_BUTTONS = 'ENABLE_BUTTONS',

    BONUS_BUY_OPENED = "BONUS_BUY_OPENED",
    BONUS_BUY_CLOSED = "BONUS_BUY_CLOSED",

    ACTIVATE_WEBSOCKET = 'ACTIVATE_WEBSOCKET',
    UPDATE_WEBSOCKET_DATA = 'UPDATE_WEBSOCKET_DATA',
}
