export enum GameEvents
{
    REGISTER_GAME = 'REGISTER_GAME',

    PRELOADING_START = 'PRELOADING_START',
    PRELOADING_PROGRESS = 'PRELOADING_PROGRESS',
    PRELOADING_DONE = 'PRELOADING_DONE',

    GAME_STARTED = 'GAME_STARTED',

    FREE_STOP_BUTTON = 'FREE_STOP_BUTTON',
    LOCK_STOP_BUTTON = 'LOCK_STOP_BUTTON',

    FINISH_PLAY = 'FINISH_PLAY',
    FINISH_SPIN = 'FINISH_SPIN',

    GET_MONEY_FORMATTER = 'GET_MONEY_FORMATTER',

    UPDATE_PAYTABLE = 'UPDATE_PAYTABLE',
    UPDATE_RULES = 'UPDATE_RULES',

    UPDATE_SIDE_BET = 'UPDATE_SIDE_BET',

    HIDE_WRAPPER_UI = 'HIDE_WRAPPER_UI',
    SHOW_WRAPPER_UI = 'SHOW_WRAPPER_UI',

    BONUS_BUY_OPENED = "BONUS_BUY_OPENED",
    BONUS_BUY_CLOSED = "BONUS_BUY_CLOSED",

    TRIGGER_EVENT = 'TRIGGER_EVENT',
    TRIGGER_EVENT_SPIN = 'TRIGGER_EVENT_SPIN',

    TRIGGER_EVENT_WEBSOCKET = 'TRIGGER_EVENT_WEBSOCKET',
    TRIGGER_UPDATE_BALANCE = 'TRIGGER_UPDATE_BALANCE',

    TRIGGER_SEND_GAMBLE = 'TRIGGER_SEND_GAMBLE',
    TRIGGER_FINISH_GAMBLE = 'TRIGGER_FINISH_GAMBLE',

    NEXT_HISTORY = 'NEXT_HISTORY',
    CLOSE_HISTORY = 'CLOSE_HISTORY'
}
