export enum WrapperEvents
{
    START_GAME = 'START_GAME',
    PRELOADING_COMPLETE = 'PRELOADING_COMPLETE',

    START_SPIN = 'START_SPIN',
    START_PLAY = 'START_PLAY',
    STOP_SPIN = 'STOP_SPIN',

    UPDATE_SETTINGS = 'UPDATE_SETTINGS',
    UPDATE_BAR_SIZES = 'UPDATE_BAR_SIZES',

    RESET_GAME = 'RESET_GAME',

    SEND_MONEY_FORMATTER = 'GET_MONEY_FORMATTER',

    EVENT_TRIGGERED = 'EVENT_TRIGGERED',
    EVENT_TRIGGERED_FAILED = 'EVENT_TRIGGERED_FAILED',

    EVENT_TRIGGERED_SPIN = 'EVENT_TRIGGERED_SPIN',

    OPEN_HISTORY = 'OPEN_HISTORY',
    UPDATE_HISTORY = 'UPDATE_HISTORY',

    START_GAMBLE = 'START_GAMBLE',
    EVENT_TRIGGERED_GAMBLE = 'EVENT_TRIGGERED_GAMBLE',
    END_GAMBLE = 'END_GAMBLE',

    BONUS_BUY_OPENED = "BONUS_BUY_OPENED",

    PAUSE_GAME = 'PAUSE_GAME',
    UNPAUSE_GAME = 'UNPAUSE_GAME',

    WEBSOCKET_ACTIVATED = 'WEBSOCKET_ACTIVATED',
    WEBSOCKET_OPEN_HISTORY = 'WEBSOCKET_OPEN_HISTORY',
    WEBSOCKET_OPEN_PLAYERS = 'WEBSOCKET_OPEN_PLAYERS',
    WEBSOCKET_SHOW_REALITYCHECK = 'WEBSOCKET_SHOW_REALITYCHECK',

    /**
     * @deprecated
     */
    EVENT_TRIGGERED_WEBSOCKET = 'EVENT_TRIGGERED_WEBSOCKET',
}