export enum WrapperEvents
{
    START_GAME = 'START_GAME',

    PRELOADING_COMPLETE = 'PRELOADING_COMPLETE',

    UPDATE_SETTINGS = 'UPDATE_SETTINGS',
    UPDATE_BAR_SIZES = 'UPDATE_BAR_SIZES',

    START_SPIN = 'START_SPIN',
    STOP_SPIN = 'STOP_SPIN',

    FAILED_SPIN = 'FAILED_SPIN',

    SEND_MONEY_FORMATTER = 'GET_MONEY_FORMATTER',

    EVENT_TRIGGERED = 'EVENT_TRIGGERED',
    EVENT_TRIGGERED_FAILED = 'EVENT_TRIGGERED_FAILED',

    EVENT_TRIGGERED_SPIN = 'EVENT_TRIGGERED_SPIN',
    EVENT_TRIGGERED_WEBSOCKET = 'EVENT_TRIGGERED_WEBSOCKET',

    OPEN_HISTORY = 'OPEN_HISTORY',
    UPDATE_HISTORY = 'UPDATE_HISTORY',

    START_GAMBLE = 'START_GAMBLE',
    EVENT_TRIGGERED_GAMBLE = 'EVENT_TRIGGERED_GAMBLE',
    END_GAMBLE = 'END_GAMBLE'
}